server:
  port: 8080
  compression:
    enabled: true

spring:
  application:
    name: websocket-chat-server
  
  # Development profile configuration
  profiles:
    active: dev
    
  # JSON configuration
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

# WebSocket configuration
websocket:
  max-sessions: 1000
  max-message-size: 1024
  connection-timeout: 30000

# CORS configuration
cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,websocket
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    com.chatapp: INFO
    org.springframework.messaging: INFO
    org.springframework.web.socket: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  profiles: dev

logging:
  level:
    com.chatapp: DEBUG
    org.springframework.messaging: DEBUG
    
---
spring:
  profiles: prod

logging:
  level:
    root: WARN
    com.chatapp: INFO